// The five phases, taken from the manual's contents page. Rework loops are
// hung off the review and verification procedures, which is where a stage-gate
// process actually sends work back from.
module.exports.phases = [
  {
    n: 1, slug: 'concept',
    name: 'Concept and Screening',
    range: 'NPDP1010 – NPDP1030',
    intent: 'Decide whether the opportunity is worth planning for, and appoint the people who will decide.',
    entry: 'Opportunity identified',
    steps: [
      { code: 'NPDP1010', title: 'Opportunity Assessment' },
      { code: 'NPDP1020', title: 'Selection of Gate Keepers' },
      { code: 'NPDP1030', title: 'Initial Screening' },
    ],
    gate: { n: 1, code: 'NPDP1030', title: 'Initial Screening' },
    loops: [
      { from: 'NPDP1030', to: 'NPDP1010', label: 'assessment incomplete' },
    ],
    deliverables: ['Opportunity assessment record', 'Appointed gate keeper panel', 'Initial screening score sheet'],
  },
  {
    n: 2, slug: 'planning',
    name: 'Definition and Planning',
    range: 'NPDP2010 – NPDP2060',
    intent: 'Fix what the product must do, open the record that will carry the project, and agree the plan.',
    entry: 'Gate 1 passed',
    steps: [
      { code: 'NPDP2010', title: 'Project Start Up (PSU)' },
      { code: 'NPDP2020', title: 'Product Design Specification (PDS)' },
      { code: 'NPDP2030', title: 'Design History File Creation', spine: true },
      { code: 'NPDP2040', title: 'Project Plan' },
      { code: 'NPDP2050', title: 'Preliminary Project Review' },
      { code: 'NPDP2060', title: 'Plan Approval' },
    ],
    gate: { n: 2, code: 'NPDP2060', title: 'Plan Approval' },
    loops: [
      { from: 'NPDP2050', to: 'NPDP2040', label: 'revise plan' },
      { from: 'NPDP2060', to: 'NPDP2020', label: 'PDS not agreed' },
    ],
    deliverables: ['Project charter', 'Approved PDS', 'Design History File opened', 'Approved project plan'],
  },
  {
    n: 3, slug: 'design',
    name: 'Design and Development',
    range: 'NPDP3010 – NPDP3130',
    intent: 'Take the specification to a verified, validated, manufacturable design.',
    entry: 'Gate 2 passed',
    steps: [
      { code: 'NPDP3010', title: 'Concept Design' },
      { code: 'NPDP3020', title: 'System Design' },
      { code: 'NPDP3030', title: 'Detail Design' },
      { code: 'NPDP3040', title: 'Design Review' },
      { code: 'NPDP3050', title: 'Process Design' },
      { code: 'NPDP3060', title: 'Alpha Prototype Build and Preliminary Testing' },
      { code: 'NPDP3070', title: 'Alpha Prototype Review' },
      { code: 'NPDP3080', title: 'Release of Pre-Production Documents' },
      { code: 'NPDP3090', title: 'Production Tooling and Equipment Planning' },
      { code: 'NPDP3100', title: 'Beta Prototype, Design Verification and Validation' },
      { code: 'NPDP3110', title: 'Manufacturability Review' },
      { code: 'NPDP3120', title: 'Intermediate Project Review' },
      { code: 'NPDP3130', title: 'Design Approval' },
    ],
    gate: { n: 3, code: 'NPDP3130', title: 'Design Approval' },
    loops: [
      { from: 'NPDP3040', to: 'NPDP3030', label: 'design not accepted' },
      { from: 'NPDP3070', to: 'NPDP3030', label: 'alpha failed' },
      { from: 'NPDP3100', to: 'NPDP3030', label: 'V&V failed' },
      { from: 'NPDP3110', to: 'NPDP3050', label: 'not manufacturable' },
    ],
    deliverables: ['Concept, system and detail design records', 'Process design and control plan',
                   'Alpha and beta prototype test reports', 'Design verification and validation records',
                   'Pre-production drawing pack'],
  },
  {
    n: 4, slug: 'validation',
    name: 'Production Validation',
    range: 'NPDP4010 – NPDP4090',
    intent: 'Prove the production process makes the design repeatably, at rate, before committing to it.',
    entry: 'Gate 3 passed',
    steps: [
      { code: 'NPDP4010', title: 'Engineering Change Order (ECO) Release', spine: true },
      { code: 'NPDP4020', title: 'Production Sourcing Preparation' },
      { code: 'NPDP4030', title: 'Production Preparation' },
      { code: 'NPDP4040', title: 'Pre-Production Prototype Development' },
      { code: 'NPDP4050', title: 'Production Verification' },
      { code: 'NPDP4060', title: 'Pre-Production Prototype Validation' },
      { code: 'NPDP4070', title: 'Production Release Design Review' },
      { code: 'NPDP4080', title: 'Project Review Before Full Scale Production' },
      { code: 'NPDP4090', title: 'Production Approval' },
    ],
    gate: { n: 4, code: 'NPDP4090', title: 'Production Approval' },
    loops: [
      { from: 'NPDP4050', to: 'NPDP4010', label: 'process capability short' },
      { from: 'NPDP4060', to: 'NPDP4010', label: 'validation failed' },
      { from: 'NPDP4070', to: 'NPDP4010', label: 'change required' },
    ],
    deliverables: ['Released ECOs', 'Approved supplier and tooling set', 'Production verification records',
                   'Validated pre-production units', 'Production release record'],
  },
  {
    n: 5, slug: 'launch',
    name: 'Launch and Feedback',
    range: 'NPDP5010 – NPDP5050',
    intent: 'Put the product and its support material into the market, then feed what happens back in.',
    entry: 'Gate 4 passed',
    steps: [
      { code: 'NPDP5010', title: 'Product Publications and Training' },
      { code: 'NPDP5020', title: 'Product Introduction Review' },
      { code: 'NPDP5030', title: 'Full-Scale Production Readiness Approval' },
      { code: 'NPDP5040', title: 'Product Launch and Full Scale Production' },
      { code: 'NPDP5050', title: 'Feedback, Assessment and Corrective Action' },
    ],
    // Gate 5 sits INSIDE this phase, not at the end of it: 5030 approves
    // readiness, and 5040 and 5050 happen after it.
    gate: { n: 5, code: 'NPDP5030', title: 'Full-Scale Production Readiness Approval', midPhase: true },
    loops: [
      { from: 'NPDP5020', to: 'NPDP5010', label: 'material not ready' },
    ],
    exits: [
      { from: 'NPDP5050', label: 'Corrective action → NPDP4010 ECO' },
      { from: 'NPDP5050', label: 'Lessons learned → NPDP1010 Opportunity Assessment' },
    ],
    deliverables: ['Operator and service publications', 'Training records', 'Launch readiness record',
                   'Field feedback and corrective action log'],
  },
];
