// Drishya mapped onto the NPD procedure set. Every "evidence" entry is a real
// artefact in the repository or a real event in its history — nothing here is
// written to fill a row.
//
// "adapted" marks a procedure written for physical product development that has
// no literal equivalent in software. It is not skipped: the note says what
// carries the same weight instead.
module.exports.phases = [
  {
    n: 1, slug: 'concept', name: 'Concept and Screening', range: 'NPDP1010 – NPDP1030',
    intent: 'Establish that vendors delivering into a fulfilment centre have a visibility gap worth closing, and fix the boundaries of what would be built.',
    entry: 'Opportunity identified',
    steps: [
      { code: 'NPDP1010', title: 'Opportunity Assessment',
        was: 'The blind stretch between two gates',
        ev: 'A delay is discovered when the delivery is refused; a paperwork error weeks later on a payment statement, dispute window already closing. Both were knowable earlier.' },
      { code: 'NPDP1020', title: 'Selection of Gate Keepers',
        was: 'ILP review panel',
        ev: 'Faculty reviewers appointed as the authority for every gate decision in this project.' },
      { code: 'NPDP1030', title: 'Initial Screening',
        was: 'Scope boundaries fixed',
        ev: 'Hardware out of scope, ingest HTTPS only, no paid APIs, no Kafka or Kubernetes, deploy target a t3.micro. Recorded in CLAUDE.md and held to throughout.' },
    ],
    gate: { n: 1, code: 'NPDP1030', title: 'Initial Screening' },
    loops: [],
  },
  {
    n: 2, slug: 'planning', name: 'Definition and Planning', range: 'NPDP2010 – NPDP2060',
    intent: 'Fix the contract the whole system would be held to, and open the record that would carry every decision.',
    entry: 'Gate 1 passed',
    steps: [
      { code: 'NPDP2010', title: 'Project Start Up (PSU)',
        was: 'Repository and environment',
        ev: 'Two independent projects — Drishya.Backend and Drishya Frontend — plus docker-compose bringing up PostgreSQL 16 with PostGIS in one command.' },
      { code: 'NPDP2020', title: 'Product Design Specification (PDS)',
        was: 'The wire contract',
        ev: 'Every enum carries an explicit @JsonValue string matching the frontend vocabulary exactly. Timestamps cross as epoch milliseconds, never ISO. promisedAt and predictedAt are both kept and neither may overwrite the other.' },
      { code: 'NPDP2030', title: 'Design History File Creation', spine: true,
        was: 'The repository and CLAUDE.md',
        ev: 'Git history is the design record; CLAUDE.md is the reasoning behind it. Every trap this project hit is written down there at the moment it was understood.' },
      { code: 'NPDP2040', title: 'Project Plan',
        was: 'Four verification layers, planned up front',
        ev: 'API, tenancy, page render and interaction journeys — chosen because each layer can pass while the one above it is broken.' },
      { code: 'NPDP2050', title: 'Preliminary Project Review',
        was: 'Architecture walkthrough',
        ev: 'Layering, tenancy boundary and the prediction seam reviewed before implementation started.' },
      { code: 'NPDP2060', title: 'Plan Approval',
        was: 'Gate 2',
        ev: 'Plan and specification accepted; build authorised.' },
    ],
    gate: { n: 2, code: 'NPDP2060', title: 'Plan Approval' },
    loops: [{ from: 'NPDP2050', to: 'NPDP2020', label: 'contract not settled' }],
  },
  {
    n: 3, slug: 'design', name: 'Design and Development', range: 'NPDP3010 – NPDP3130',
    intent: 'Build the platform and prove it works — including proving it does not leak one customer’s data to another.',
    entry: 'Gate 2 passed',
    steps: [
      { code: 'NPDP3010', title: 'Concept Design',
        was: 'One shipment, three portals',
        ev: 'A single shipment object with three bounded views: the vendor who books it, the driver who carries it, the fulfilment centre that receives it.' },
      { code: 'NPDP3020', title: 'System Design',
        was: 'Layering and the choke points',
        ev: 'domain / repo / dto / service / web, with tenant filtering in the repository layer. On the browser side every call goes through services/client.js; nothing calls fetch directly.' },
      { code: 'NPDP3030', title: 'Detail Design',
        was: 'The implementation',
        ev: '170 Java source files, 124 frontend source files, 13 Flyway migrations, schema managed with ddl-auto off.' },
      { code: 'NPDP3040', title: 'Design Review',
        was: 'Tenancy review',
        ev: 'Commit 7256c8b records the findings: every inherited listing endpoint was returning all tenants’ rows to any authenticated caller.' },
      { code: 'NPDP3050', title: 'Process Design',
        was: 'The verification estate',
        ev: 'Testcontainers against real PostGIS because H2 cannot answer ST_DWithin; Playwright for the two browser layers; a tenancy audit script that probes every write path.' },
      { code: 'NPDP3060', title: 'Alpha Prototype Build and Preliminary Testing',
        was: 'v0.1, 15 August',
        ev: 'Commit 45cae0a — "v0.1 working full-stack Drishya". First build where a consignment could be booked, driven and received end to end.' },
      { code: 'NPDP3070', title: 'Alpha Prototype Review',
        was: 'Isolation found to be one-sided',
        ev: 'The receiving desk is deliberately cross-tenant, and that hid the fact it is still bounded to one site. Bhiwandi could read Manesar’s board and gate its vehicles out.' },
      { code: 'NPDP3080', title: 'Release of Pre-Production Documents',
        was: 'README, CLAUDE.md, DEPLOYMENT.md, OpenAPI',
        ev: 'Swagger UI at /swagger-ui.html and the document at /v3/api-docs, both public; the endpoints they describe are not.' },
      { code: 'NPDP3090', title: 'Production Tooling and Equipment Planning', adapted: true,
        was: 'Build and deployment toolchain',
        ev: 'No physical tooling exists. Standing in its place: the two Dockerfiles, docker-compose, the CloudFormation template, and the Testcontainers and Playwright estates that any build must pass.' },
      { code: 'NPDP3100', title: 'Beta Prototype, Design Verification and Validation',
        was: 'Four suites, 147 checks',
        ev: '82 API assertions signed in as two vendors; every write path probed as the wrong tenant, every line must read blocked; 39 pages in a real browser as every role; 26 interaction journeys.' },
      { code: 'NPDP3110', title: 'Manufacturability Review',
        was: 'Will it run on the target box',
        ev: 'Hikari pool capped at 5 and the JVM footprint kept modest, because the deploy target is a t3.micro with a db.t4g.micro behind it.' },
      { code: 'NPDP3120', title: 'Intermediate Project Review',
        was: 'Pre-deployment review',
        ev: 'Verification estate green, isolation proven with two tenants, documentation released.' },
      { code: 'NPDP3130', title: 'Design Approval',
        was: 'Gate 3',
        ev: 'Design accepted; deployment authorised.' },
    ],
    gate: { n: 3, code: 'NPDP3130', title: 'Design Approval' },
    loops: [
      { from: 'NPDP3040', to: 'NPDP3030', label: '7 endpoints leaking' },
      { from: 'NPDP3070', to: 'NPDP3030', label: 'FC site isolation' },
      { from: 'NPDP3100', to: 'NPDP3030', label: 'browser authored state' },
      { from: 'NPDP3110', to: 'NPDP3050', label: 'clocks disagreed' },
    ],
  },
  {
    n: 4, slug: 'validation', name: 'Production Validation', range: 'NPDP4010 – NPDP4090',
    intent: 'Prove the thing runs on real infrastructure, under real constraints, before anyone is asked to look at it.',
    entry: 'Gate 3 passed',
    steps: [
      { code: 'NPDP4010', title: 'Engineering Change Order (ECO) Release', spine: true,
        was: 'Every fix, as a commit',
        ev: '73 commits on main between 15 August and 14 September. Each carries what was wrong, why it was not visible, and how it was proven fixed.' },
      { code: 'NPDP4020', title: 'Production Sourcing Preparation', adapted: true,
        was: 'Cloud resource selection',
        ev: 'No supplier sourcing. Instead: region ap-south-1, EC2 plus RDS sized deliberately, and three things ruled out for billing hourly — load balancer, NAT gateway, multi-AZ.' },
      { code: 'NPDP4030', title: 'Production Preparation',
        was: 'One CloudFormation stack',
        ev: 'aws/drishya.cfn.yaml brings up the whole environment and one delete-stack removes it. Secrets reach the instance through user data, never the repository.' },
      { code: 'NPDP4040', title: 'Pre-Production Prototype Development',
        was: 'The deployed instance',
        ev: 'Images built on the instance rather than pushed, because the upload link could not sustain a push to ECR.' },
      { code: 'NPDP4050', title: 'Production Verification',
        was: 'What only the real environment showed',
        ev: 'Three faults invisible locally: the router mislabelling its reply encoding so every booking drew a straight line; the root volume filling until a deploy died inside a build layer; the API wedging with only a reboot to recover it.' },
      { code: 'NPDP4060', title: 'Pre-Production Prototype Validation',
        was: 'The three-role journey, deployed',
        ev: 'Vendor books, driver starts and carries, receiving desk books the dock and raises the goods receipt — on the deployed site, as three separate signed-in accounts.' },
      { code: 'NPDP4070', title: 'Production Release Design Review',
        was: 'Codebase audit',
        ev: 'A full pass over tenancy, authorisation and the write paths, with the residual gaps written down rather than quietly closed.' },
      { code: 'NPDP4080', title: 'Project Review Before Full Scale Production',
        was: 'Readiness review',
        ev: 'Memory limit, watchdog and disk reclamation in place so the environment recovers without a human.' },
      { code: 'NPDP4090', title: 'Production Approval',
        was: 'Gate 4',
        ev: 'Environment accepted for demonstration.' },
    ],
    gate: { n: 4, code: 'NPDP4090', title: 'Production Approval' },
    loops: [
      { from: 'NPDP4050', to: 'NPDP4010', label: 'routing fell back' },
      { from: 'NPDP4050', to: 'NPDP4010', label: 'disk exhausted' },
      { from: 'NPDP4060', to: 'NPDP4010', label: 'API wedged' },
    ],
  },
  {
    n: 5, slug: 'launch', name: 'Launch and Feedback', range: 'NPDP5010 – NPDP5050',
    intent: 'Put the product and its documentation in front of the panel, and route what comes back into the change process.',
    entry: 'Gate 4 passed',
    steps: [
      { code: 'NPDP5010', title: 'Product Publications and Training',
        was: 'Final MVP Report and demo accounts',
        ev: 'The report covers purpose, components, source, outputs, issues and setup. Three one-click demo accounts so a reviewer never types a password.' },
      { code: 'NPDP5020', title: 'Product Introduction Review',
        was: 'Walkthrough rehearsal',
        ev: 'Every screen checked as every role against a freshly seeded database.' },
      { code: 'NPDP5030', title: 'Full-Scale Production Readiness Approval',
        was: 'Gate 5',
        ev: 'Readiness confirmed before the demonstration, not after.' },
      { code: 'NPDP5040', title: 'Product Launch and Full Scale Production',
        was: 'The ILP demonstration',
        ev: 'The deployed site, driven live through the three portals.' },
      { code: 'NPDP5050', title: 'Feedback, Assessment and Corrective Action',
        was: 'Findings routed back as ECOs',
        ev: 'A consignment booked through the form never reached the receiving desk’s board. Root cause: the promised slot was a flat 36 hours from booking. Now costed from the pickup time against the same lane history the engine uses.' },
    ],
    gate: { n: 5, code: 'NPDP5030', title: 'Full-Scale Production Readiness Approval', midPhase: true },
    loops: [],
    exits: [
      { from: 'NPDP5050', label: 'Corrective action → NPDP4010 ECO' },
      { from: 'NPDP5050', label: 'Lessons learned → NPDP1010' },
    ],
  },
];
