package com.drishya.backend.domain.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Where a position fix came from.
 *
 * <p><b>This column is not bookkeeping.</b> The evidence pack is a chargeback
 * dispute artefact, and a fix generated by the simulator does not carry the
 * same weight as one a driver's browser reported from the cab. Blending them
 * would let a demo trace be presented as observed truth, so every position
 * records its provenance and every API response exposes it.
 */
public enum PositionSource {

    /** Produced by the simulator. Reproducible, and not evidence of anything. */
    SIMULATED("simulated"),

    /** Reported by a real device through the browser geolocation API. */
    BROWSER("browser");

    private final String wire;

    PositionSource(String wire) {
        this.wire = wire;
    }

    @JsonValue
    public String wire() {
        return wire;
    }

    /** True if a fix from this source may be cited in a dispute. */
    public boolean isEvidential() {
        return this == BROWSER;
    }

    @JsonCreator
    public static PositionSource from(String value) {
        if (value == null) {
            return null;
        }
        for (PositionSource candidate : values()) {
            if (candidate.wire.equalsIgnoreCase(value) || candidate.name().equalsIgnoreCase(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException("Unknown PositionSource: " + value);
    }
}
