#!/usr/bin/env bash
# Deploys Drishya to AWS, end to end.
#
#   ./aws/deploy.sh
#
# Every phase is idempotent and the script is safe to re-run: CloudFormation
# reconciles, the extension creation is IF NOT EXISTS, and the image push and
# bundle sync overwrite. If it dies halfway, fix the cause and run it again.
#
# It exists because the manual sequence in AWS-DEPLOYMENT.md has one step that
# is genuinely fiddly — enabling PostGIS on a database that is deliberately
# unreachable from your laptop, which means going in through the instance. That
# step is also the one that fails silently if you skip it: the container starts,
# Flyway cannot create a geography column, and the API answers 500 to
# everything while looking perfectly healthy in the console.
#
# ORDER MATTERS, IN ONE PLACE. PostGIS must exist before the API first boots.
# The stack creates the instance before there is an image to run and the
# instance waits for one, which is what buys us the gap to enable the extension
# in. Pushing the image first is not fatal — the container restarts until the
# migration succeeds — but it fills the logs with failures that look like a
# broken build.
set -euo pipefail

REGION="${REGION:-ap-south-1}"
STACK="${STACK:-drishya}"
SECRETS_FILE="${SECRETS_FILE:-.aws-secrets.env}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
die()  { printf '\n\033[31merror: %s\033[0m\n' "$*" >&2; exit 1; }

out() { # stack output by key
    aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
        --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

# --- 0. preflight ----------------------------------------------------------

say "Checking prerequisites"
command -v aws    >/dev/null || die "aws CLI not found."
command -v docker >/dev/null || die "docker not found — needed to build the API image."
command -v npm    >/dev/null || die "npm not found — needed to build the bundle."
aws sts get-caller-identity >/dev/null 2>&1 \
    || die "AWS credentials are not working. Run: aws configure"

echo "account : $(aws sts get-caller-identity --query Account --output text)"
echo "region  : $REGION"
echo "stack   : $STACK"

# --- 1. the CloudFront prefix list ----------------------------------------

say "Looking up the CloudFront origin-facing prefix list"
PREFIX_LIST=$(aws ec2 describe-managed-prefix-lists --region "$REGION" \
    --filters Name=prefix-list-name,Values=com.amazonaws.global.cloudfront.origin-facing \
    --query 'PrefixLists[0].PrefixListId' --output text)
if [ -z "$PREFIX_LIST" ] || [ "$PREFIX_LIST" = "None" ]; then
    die "Could not find the CloudFront prefix list in $REGION."
fi
echo "$PREFIX_LIST"

# --- 2. secrets ------------------------------------------------------------
#
# Generated once and kept, because a re-run with a different database password
# would ask CloudFormation to change the master password on a live instance,
# while the container carries on using the old one.

if [ -f "$SECRETS_FILE" ]; then
    say "Reusing secrets from $SECRETS_FILE"
    # shellcheck disable=SC1090
    . "$SECRETS_FILE"
else
    say "Generating secrets into $SECRETS_FILE"
    DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/@" ' | cut -c1-32)
    JWT_SECRET=$(openssl rand -base64 48)
    ( umask 077; cat > "$SECRETS_FILE" <<ENV
# Generated by aws/deploy.sh. Keep this. Not in git — see .gitignore.
DB_PASSWORD='$DB_PASSWORD'
JWT_SECRET='$JWT_SECRET'
ENV
    )
    echo "Written. Do not lose it: the stack will not show these back."
fi
if [ -z "${DB_PASSWORD:-}" ] || [ -z "${JWT_SECRET:-}" ]; then
    die "Secrets missing from $SECRETS_FILE."
fi

# --- 3. the stack ----------------------------------------------------------

say "Deploying the stack (15-20 minutes on a first run)"
aws cloudformation deploy \
    --region "$REGION" \
    --stack-name "$STACK" \
    --template-file aws/drishya.cfn.yaml \
    --capabilities CAPABILITY_IAM \
    --no-fail-on-empty-changeset \
    --parameter-overrides \
        DbPassword="$DB_PASSWORD" \
        JwtSecret="$JWT_SECRET" \
        CloudFrontPrefixListId="$PREFIX_LIST"

INSTANCE=$(out InstanceId)
DB_HOST=$(out DbEndpoint)
ECR=$(out EcrRepository)
BUCKET=$(out BundleBucket)
DIST=$(out DistributionId)
SITE=$(out SiteUrl)

echo "instance: $INSTANCE"
echo "database: $DB_HOST"
echo "site    : $SITE"

# --- 4. PostGIS ------------------------------------------------------------
#
# Through the instance, because the database admits nothing else. Session
# Manager rather than SSH, so this needs no key pair and no open port.

say "Waiting for the instance to register with Session Manager"
registered=0
for _ in $(seq 1 40); do
    registered=$(aws ssm describe-instance-information --region "$REGION" \
        --filters "Key=InstanceIds,Values=$INSTANCE" \
        --query 'length(InstanceInformationList)' --output text 2>/dev/null || echo 0)
    [ "$registered" = "1" ] && break
    sleep 15
done
[ "$registered" = "1" ] || die "Instance never registered with SSM. Check the instance role."

say "Enabling PostGIS"
CMD_ID=$(aws ssm send-command --region "$REGION" \
    --instance-ids "$INSTANCE" \
    --document-name AWS-RunShellScript \
    --comment "Enable PostGIS" \
    --parameters commands="[\"set -e\",\"dnf install -y postgresql16 >/dev/null\",\"export PGPASSWORD='$DB_PASSWORD'\",\"psql -h $DB_HOST -U drishya -d drishya -v ON_ERROR_STOP=1 -c 'CREATE EXTENSION IF NOT EXISTS postgis;'\",\"psql -h $DB_HOST -U drishya -d drishya -tAc \\\"SELECT extname||' '||extversion FROM pg_extension WHERE extname='postgis'\\\"\"]" \
    --query 'Command.CommandId' --output text)

aws ssm wait command-executed --region "$REGION" \
    --command-id "$CMD_ID" --instance-id "$INSTANCE" 2>/dev/null || true

STATUS=$(aws ssm get-command-invocation --region "$REGION" \
    --command-id "$CMD_ID" --instance-id "$INSTANCE" --query Status --output text)
POSTGIS=$(aws ssm get-command-invocation --region "$REGION" \
    --command-id "$CMD_ID" --instance-id "$INSTANCE" --query StandardOutputContent --output text)

if [ "$STATUS" != "Success" ]; then
    aws ssm get-command-invocation --region "$REGION" \
        --command-id "$CMD_ID" --instance-id "$INSTANCE" \
        --query StandardErrorContent --output text >&2
    die "Could not enable PostGIS. Nothing else will work until this does."
fi
echo "$POSTGIS" | grep -q postgis \
    || die "PostGIS reported no version. Stop here — every geofence and lane query needs it."
echo "$POSTGIS"

# --- 5. the API image ------------------------------------------------------
#
# Built here rather than on the instance: a Maven build inside a container on
# 1 GB of RAM is a coin toss, and losing it gives an OOM-killed process rather
# than a compile error.

say "Building and pushing the API image"
aws ecr get-login-password --region "$REGION" \
    | docker login --username AWS --password-stdin "${ECR%%/*}"
docker build -t "$ECR:latest" Drishya.Backend
docker push "$ECR:latest"

say "Restarting the container onto the new image"
# On a first run the instance is still in its pull-and-wait loop and will find
# the image by itself; this makes a re-run pick up a new build too.
aws ssm send-command --region "$REGION" \
    --instance-ids "$INSTANCE" \
    --document-name AWS-RunShellScript \
    --comment "Restart drishya-api" \
    --parameters commands="[\"docker pull $ECR:latest\",\"docker rm -f drishya-api 2>/dev/null || true\",\"docker run -d --name drishya-api --restart always -p 8080:8080 --env-file /etc/drishya.env -e JAVA_TOOL_OPTIONS='-Xmx512m -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC' $ECR:latest\"]" \
    --query 'Command.CommandId' --output text >/dev/null

# --- 6. the bundle ---------------------------------------------------------
#
# No VITE_API_BASE. It defaults to /api, which is correct because the API is on
# the same origin. An absolute URL here would reintroduce the cross-origin
# request this architecture exists to avoid.

say "Building the frontend bundle"
( cd "Drishya Frontend/drishya_frontend" && npm ci --silent && npm run build )

say "Uploading to S3"
BUNDLE="Drishya Frontend/drishya_frontend/dist"
# Fingerprinted assets first and cached hard; index.html last and uncached,
# because it is the file that points at the new fingerprints.
aws s3 sync "$BUNDLE/" "s3://$BUCKET/" --delete --only-show-errors \
    --exclude index.html --cache-control "public,max-age=31536000,immutable"
aws s3 cp "$BUNDLE/index.html" "s3://$BUCKET/index.html" --only-show-errors \
    --cache-control "no-cache"

aws cloudfront create-invalidation --region "$REGION" \
    --distribution-id "$DIST" --paths "/index.html" "/" \
    --query 'Invalidation.Id' --output text >/dev/null

# --- 7. verify -------------------------------------------------------------

say "Waiting for the API to answer"
for _ in $(seq 1 40); do
    if curl -fsS "$SITE/actuator/health/readiness" >/dev/null 2>&1; then
        healthy=yes; break
    fi
    sleep 15
done

if [ "${healthy:-}" != "yes" ]; then
    cat >&2 <<TROUBLE

The site is up but the API is not answering yet.

The distribution can take a few more minutes to propagate on a first deploy.
If it stays down, look at the container:

    aws ssm start-session --region $REGION --target $INSTANCE
    sudo docker logs drishya-api

TROUBLE
    exit 1
fi

curl -fsS -XPOST "$SITE/api/auth/demo-login" \
     -H 'Content-Type: application/json' -d '{"role":"vendor_admin"}' >/dev/null \
    || die "Health is up but demo-login failed. Check the container logs."

cat <<DONE

  Deployed.

    $SITE

  Sign in as priya@anandauto.example / drishya, book a consignment, and press
  Start trip — the server drives it with nothing open.

  When you are done, and DO put the date in your calendar:

    scripts/teardown.sh aws

DONE
