package com.drishya.backend.dto;

import com.drishya.backend.domain.enums.PositionSource;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

import java.util.List;

/**
 * What crosses the wire on the ingest path.
 *
 * <p><b>Plain doubles, never a JTS type.</b> Jackson 3 changed group IDs and
 * class names, and the JTS datatype module has no dependable Jackson 3 build —
 * serialising a Point directly is a runtime failure waiting for the first
 * response that contains one. Geometry is built in the service layer from these
 * numbers and never travels back out as anything else.
 */
public final class PositionDtos {

    private PositionDtos() {
    }

    /**
     * One fix as reported by a device.
     *
     * <p>Note what is absent: there is no received-time field. The server stamps
     * that itself, because a client that could set its own receive time could
     * rewrite the record of when a delay became known — which is the record a
     * chargeback dispute turns on.
     */
    public record PositionReport(

            @NotNull
            @DecimalMin(value = "-90.0", message = "Latitude must be between -90 and 90.")
            @DecimalMax(value = "90.0", message = "Latitude must be between -90 and 90.")
            Double lat,

            @NotNull
            @DecimalMin(value = "-180.0", message = "Longitude must be between -180 and 180.")
            @DecimalMax(value = "180.0", message = "Longitude must be between -180 and 180.")
            Double lon,

            @PositiveOrZero(message = "Speed cannot be negative.")
            Double speedKmph,

            Double headingDeg,

            /** Epoch milliseconds, matching every other timestamp in this API. */
            @NotNull(message = "Every fix must carry the time it was taken.")
            Long deviceTimestamp,

            /**
             * Where the fix came from. Required rather than defaulted: a fix
             * that silently defaults to BROWSER would be admissible evidence
             * generated by a simulator, and defaulting the other way would
             * quietly devalue real driver data. The caller must say.
             */
            @NotNull(message = "Every fix must declare its source.")
            PositionSource source) {
    }

    /**
     * A batch of fixes for one trip.
     *
     * <p>Batched because a vehicle emerging from a dead zone has buffered
     * several minutes of fixes and needs to deliver them in one request. The
     * cap is a guard against a client replaying an entire journey in a single
     * call and holding a connection open while it is written.
     */
    public record PositionBatch(
            @NotEmpty(message = "A batch must contain at least one fix.")
            @Size(max = 500, message = "Send at most 500 fixes per batch.")
            @Valid List<PositionReport> positions) {
    }

    /**
     * The 202 body. Deliberately thin: the request thread has done nothing but
     * validate and persist, and the geofence and ETA work happens after the
     * response has gone.
     */
    public record IngestAck(
            String tripId,
            int accepted,
            int rejected,
            List<String> rejections,
            long receivedAt) {
    }

    /** One stored fix, on the way back out. */
    public record PositionView(
            long id,
            double lat,
            double lon,
            Double speedKmph,
            Double headingDeg,
            long deviceTimestamp,
            long receivedAt,
            PositionSource source,
            long latencySeconds) {
    }
}
